### ISSUE TITLE
重构计划还有效吗？

### ISSUE THREAD

**Issue by little-buddy** [Linkontoask/radishes#5]
话说19年12月底最后一次更新，这个计划是被搁浅了吗？

**Comment by Linkontoask** [comment]
vue-next未发布正式版 [https://github.com/vuejs/vue-next](https://github.com/vuejs/vue-next)

**Comment by Linkontoask** [comment]
vue已发布，启动重构计划，先进行一些简短的rfc后正式开展重构工作
